# https://numtide.github.io/devshell
[[commands]]
package = "cloud-init"

[[commands]]
package = "python3"

[[commands]]
package = "qemu"

[[commands]]
package = "just"

[[commands]]
package = "cdrkit"
